people_name_first='Oscar1'
people_name_last='Madisox1'
people_name_gender='Female'

people_address_add_line1='viman_nagar'
people_address_add_line2='South_Gate'
people_address_city='Pune'
people_address_state='OK'
people_address_zip='11223'

people_phone_home='111-222-3000'
people_phone_work='888-999-7777'
people_phone_mobile='444-555-6666'

people_email_personal='Akshata@gmail.com'
people_email_work='Akshata@testrig.com'
people_comments='Active'

company_name='XYZ'
company_address_line1='Hinjewadi'
company_address_line2='Phase2'
company_address_city='Mumbai'
company_address_state='OK'
company_address_zip='10001'

company_phone_main='222-333-4000'
company_phone_other='444-555-6000' 
comments='All_Ok'

generic_1='Text1'
generic_2='Text2'
generic_3='Text3'
generic_4='Text4'
generic_5='Text5'
generic_6='Text6'
generic_7='Text7'
generic_8='Text8'
generic_9='Text9'
generic_10='Text10'
application_path='C://Users//admin//Documents//MyCRM.exe'

